### ISSUE TITLE
Accessing suffixarray of text with UTF8 values is unclear

### ISSUE THREAD

**Issue by fpmenninger** [JuliaCollections/SuffixArrays.jl#14]
The first paragraph in the docs
> The suffixsort function can compute a suffix array for vectors of UInt8 or UInt16 values, or for strings with code units that are one of these two types. When generating a suffix array for a string, the suffix indices are in terms of code units, not characters, which means that some indices will be into the middle of characters that span multiple code units. For UTF-8 and UTF-16 this doesn't affect using the suffix array as search index since a valid substring cannot start in the middle of a character anyway. In other words, invalid substrings occuring in the suffix array will simply not match.

is a bit confusing.  The documentation seems to indicate that Unicode characters (UTF16) can be used, but the following fails.  

```
julia> s = "бабушка\$"
julia> sa = suffixsort(s)
15-element Array{UInt8,1}:
 0x0f
 0x08
 0x0a
 0x0e
 0x04
 0x02
 0x06
 0x0c
 0x0d
 0x03
 0x01
 0x05
 0x0b
 0x07
 0x09
julia> [s[i:end] for i in sa]
ERROR: StringIndexError("бабушка\$", 8)
Stacktrace:
 [1] string_index_err(::String, ::Int64) at .\strings\string.jl:12
 [2] getindex(::String, ::UnitRange{Int64}) at .\strings\string.jl:245
 [3] (::getfield(Main, Symbol("##5#6")))(::UInt8) at .\range.jl:0
 [4] iterate at .\generator.jl:47 [inlined]
 [5] collect_to!(::Array{String,1}, ::Base.Generator{Array{UInt8,1},getfield(Main, Symbol("##5#6"))}, ::Int64, ::Int64) at .\array.jl:656
 [6] collect_to_with_first!(::Array{String,1}, ::String, ::Base.Generator{Array{UInt8,1},getfield(Main, Symbol("##5#6"))}, ::Int64) at .\array.jl:643
 [7] collect(::Base.Generator{Array{UInt8,1},getfield(Main, Symbol("##5#6"))}) at .\array.jl:624
 [8] top-level scope at none:0
```

As a side note, I wrote a julian version of sais and made Unicode possible by using something like the Unicode.grapheme iterator. (I don't think it existed then.)
Converting the Unicode text to a data array to feed to sais, I used the precomputation
 `[IntSA(c) for c in text]` 
where IntSA was the smallest UInt size that would fit all characters in text.  Thus, no "indices into the middle of characters that span multiple code units".  

Might that be something to consider?

```
julia> suffixarray("бабушка\$")
9-element Array{UInt16,1}:
 0x0008
 0x0007
 0x0006
 0x0001
 0x0000
 0x0002
 0x0005
 0x0003
 0x0004

**Comment by StefanKarpinski** [comment]
Sorting graphemes would be much slower and doesn't give indices into the original string data. The point of that paragraph is that while some suffixes will not start at valid UTF-8 indices (as your example shows), if you search for a valid UTF-8 substring, you'll get the index of a valid UTF-8 substring. Since the use cases of suffix arrays are to accelerate searches, not to actually list all valid UTF-8 suffixes in order (if that's what you want, just skip invalid indices), this is fine. The only issue with the example you give is that substring indexing doesn't like slicing strings at invalid indices, but we can work around that by slicing code units instead:
```jl
julia> [String(codeunits(s)[i:end]) for i in sa]
15-element Array{String,1}:
 "\$"
 "\x83шка\$"
 "\x88ка\$"
 "\xb0\$"
 "\xb0бушка\$"
 "\xb1абушка\$"
 "\xb1ушка\$"
 "\xbaа\$"
 "а\$"
 "абушка\$"
 "бабушка\$"
 "бушка\$"
 "ка\$"
 "ушка\$"
 "шка\$"
```
Converting the string into a grapheme seems both inefficient—it's slow and will blow up your memory usage by 4x—and unhelpful since then you'll get grapheme indices, not indices into the original string data. If you want to convert back into indices into the original string, you need to do an O(n) conversion of each index, making the whole process O(n^2) in the string length, which is slower than computing the suffix array in the first place. If that's what you want to work with graphemes, just collect the graphemes first and work with that array instead of the strings.
